const Library=(()=>{
const API='/api/library';
const session=()=>{try{const p=JSON.parse(sessionStorage.getItem('bionestSession')||'null');return{profile:p,username:p?.username||'',password_sha256:sessionStorage.getItem('bionestAuthHash')||''};}catch{return{profile:null,username:'',password_sha256:''}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatDate=v=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v));
const size=b=>{if(!b)return'0 B';const u=['B','KB','MB'];let n=b,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return n.toFixed(i?1:0)+' '+u[i]};
async function list(){const r=await fetch(API+'?v='+Date.now(),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Library gagal dimuat.');return d.items||[];}
async function request(payload){const a=session();if(!a.username||!a.password_sha256)throw new Error('Login dulu untuk memakai Library.');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,...a})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Permintaan gagal.');return d;}
function fileUrl(i){return'https://raw.githubusercontent.com/raaps199-netizen/xib1-sman1klapanunggal/main/'+i.path}
function card(i,manage=false){const icon=i.type==='article'?'pen-line':(i.mime==='application/pdf'?'file-text':'file-type-2');const action=i.type==='article'?'<a href="article.html?id='+encodeURIComponent(i.id)+'" class="inline-flex items-center gap-2 text-xs font-bold text-techCyan hover:text-white transition">Baca <i data-lucide="arrow-up-right" class="w-4 h-4"></i></a>':'<a href="'+fileUrl(i)+'" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-2 text-xs font-bold text-techCyan hover:text-white transition">Buka file <i data-lucide="download" class="w-4 h-4"></i></a>';return '<article class="library-card group p-5 rounded-2xl bg-techCard border border-slate-800 hover:border-cyan-500/35 transition"><div class="flex items-start justify-between gap-4"><div class="library-icon"><i data-lucide="'+icon+'" class="w-5 h-5"></i></div><span class="px-2.5 py-1 rounded-full bg-cyan-950/60 border border-cyan-500/15 text-cyan-300 text-[10px] font-bold uppercase tracking-wider">'+esc(i.category)+'</span></div><h3 class="text-lg font-bold mt-4 leading-snug group-hover:text-techCyan transition">'+esc(i.title)+'</h3><p class="text-xs text-slate-400 mt-2 line-clamp-2 leading-relaxed">'+esc(i.excerpt||i.description||'Belum ada deskripsi.')+'</p><div class="flex items-center justify-between gap-3 mt-5 pt-4 border-t border-slate-800"><div class="min-w-0"><p class="text-xs text-slate-300 truncate">'+esc(i.author)+'</p><p class="text-[10px] text-slate-600 mt-1">'+formatDate(i.created_at)+(i.size?' • '+size(i.size):'')+'</p></div><div class="shrink-0 flex items-center gap-3">'+action+(manage?'<button data-delete-id="'+esc(i.id)+'" class="text-xs text-red-300 hover:text-red-200">Hapus</button>':'')+'</div></div></article>'}
return{list,request,session,esc,formatDate,size,fileUrl,card};})();